### ISSUE TITLE
{"Laravel":"9.51.0"} message after completed setup

### ISSUE THREAD

**Issue by PonlorkBeang** [codenteq/imtihan#96]
# Bug Report

## eExam Version

- [ ] #97

**Comment by ahmetarsiv** [comment]
Hi, @PonlorkBeang

first of all, thank you for your interest.
After completing the installation according to the documentation, open localhost:3000 on the local server.

Follow the link for Installation Documents.
https://imtihan-docs.vercel.app/imtihan-docs/installation
